

server-tcp: server-tcp.c
	gcc server-tcp.c -o server-tcp

client-tcp: client-tcp.c
	gcc client-tcp.c -o client-tcp

server-udp: server-udp.c
	gcc server-udp.c -o server-udp

client-udp: client-udp.c
	gcc client-udp.c -o client-udp

clean:
	@rm server-tcp client-tcp server-udp client-udp

